// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IPRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPRequest) Reset()         { *m = IPRequest{} }
func (m *IPRequest) String() string { return proto.CompactTextString(m) }
func (*IPRequest) ProtoMessage()    {}
func (*IPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_82a49c426417a499, []int{0}
}
func (m *IPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPRequest.Unmarshal(m, b)
}
func (m *IPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPRequest.Marshal(b, m, deterministic)
}
func (dst *IPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPRequest.Merge(dst, src)
}
func (m *IPRequest) XXX_Size() int {
	return xxx_messageInfo_IPRequest.Size(m)
}
func (m *IPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IPRequest proto.InternalMessageInfo

func (m *IPRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type IPReply struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPReply) Reset()         { *m = IPReply{} }
func (m *IPReply) String() string { return proto.CompactTextString(m) }
func (*IPReply) ProtoMessage()    {}
func (*IPReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_82a49c426417a499, []int{1}
}
func (m *IPReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPReply.Unmarshal(m, b)
}
func (m *IPReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPReply.Marshal(b, m, deterministic)
}
func (dst *IPReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPReply.Merge(dst, src)
}
func (m *IPReply) XXX_Size() int {
	return xxx_messageInfo_IPReply.Size(m)
}
func (m *IPReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IPReply.DiscardUnknown(m)
}

var xxx_messageInfo_IPReply proto.InternalMessageInfo

func (m *IPReply) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *IPReply) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// The request message containing the user's name.
type HelloRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_82a49c426417a499, []int{2}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *HelloRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_82a49c426417a499, []int{3}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*IPRequest)(nil), "helloworld.IPRequest")
	proto.RegisterType((*IPReply)(nil), "helloworld.IPReply")
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetClientIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (Greeter_GetClientIPClient, error)
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (Greeter_RouteChatClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetClientIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (Greeter_GetClientIPClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/helloworld.Greeter/GetClientIP", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterGetClientIPClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_GetClientIPClient interface {
	Recv() (*IPReply, error)
	grpc.ClientStream
}

type greeterGetClientIPClient struct {
	grpc.ClientStream
}

func (x *greeterGetClientIPClient) Recv() (*IPReply, error) {
	m := new(IPReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (Greeter_RouteChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[1], "/helloworld.Greeter/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterRouteChatClient{stream}
	return x, nil
}

type Greeter_RouteChatClient interface {
	Send(*IPReply) error
	Recv() (*IPReply, error)
	grpc.ClientStream
}

type greeterRouteChatClient struct {
	grpc.ClientStream
}

func (x *greeterRouteChatClient) Send(m *IPReply) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterRouteChatClient) Recv() (*IPReply, error) {
	m := new(IPReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetClientIP(*IPRequest, Greeter_GetClientIPServer) error
	RouteChat(Greeter_RouteChatServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetClientIP_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IPRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).GetClientIP(m, &greeterGetClientIPServer{stream})
}

type Greeter_GetClientIPServer interface {
	Send(*IPReply) error
	grpc.ServerStream
}

type greeterGetClientIPServer struct {
	grpc.ServerStream
}

func (x *greeterGetClientIPServer) Send(m *IPReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_RouteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).RouteChat(&greeterRouteChatServer{stream})
}

type Greeter_RouteChatServer interface {
	Send(*IPReply) error
	Recv() (*IPReply, error)
	grpc.ServerStream
}

type greeterRouteChatServer struct {
	grpc.ServerStream
}

func (x *greeterRouteChatServer) Send(m *IPReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterRouteChatServer) Recv() (*IPReply, error) {
	m := new(IPReply)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetClientIP",
			Handler:       _Greeter_GetClientIP_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _Greeter_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_helloworld_82a49c426417a499) }

var fileDescriptor_helloworld_82a49c426417a499 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x4d, 0xfd, 0x53, 0x3b, 0x8a, 0x2e, 0x23, 0x4a, 0x59, 0x11, 0x96, 0x1e, 0xa4, 0x17,
	0x4b, 0xd1, 0xa3, 0xe8, 0x61, 0xf7, 0xb0, 0xee, 0xad, 0xd4, 0x83, 0xe7, 0xaa, 0x43, 0xb7, 0x90,
	0x9a, 0x98, 0x64, 0xd1, 0x7e, 0x40, 0xbf, 0x97, 0x24, 0x74, 0xdd, 0xb0, 0xd4, 0xdb, 0x64, 0xde,
	0xfb, 0xcd, 0x4b, 0x32, 0x30, 0x5a, 0x12, 0xe7, 0xe2, 0x4b, 0x28, 0xfe, 0x9e, 0x49, 0x25, 0x8c,
	0x40, 0xd8, 0x74, 0x92, 0x2b, 0x88, 0x16, 0x45, 0x49, 0x9f, 0x2b, 0xd2, 0x06, 0x47, 0xb0, 0xdb,
	0xea, 0x3a, 0x66, 0x13, 0x96, 0x46, 0xa5, 0x2d, 0x93, 0x1b, 0x08, 0xad, 0x2c, 0x79, 0x87, 0x27,
	0x10, 0x34, 0xb2, 0xd7, 0x82, 0x46, 0x22, 0xc2, 0x9e, 0x14, 0xca, 0xc4, 0xc1, 0x84, 0xa5, 0xfb,
	0xa5, 0xab, 0x93, 0x1c, 0x8e, 0x9f, 0xec, 0xec, 0xf5, 0xc0, 0x6d, 0xa6, 0x0f, 0x08, 0x36, 0x01,
	0xd7, 0x00, 0x3d, 0x61, 0x33, 0x62, 0x08, 0x5b, 0xd2, 0xba, 0xaa, 0xa9, 0x87, 0xd6, 0xc7, 0xdb,
	0x1f, 0x06, 0xe1, 0x5c, 0x11, 0x19, 0x52, 0xf8, 0x08, 0x87, 0xcf, 0x55, 0xe7, 0x30, 0x8c, 0x33,
	0xef, 0x79, 0x7e, 0xf6, 0xf8, 0x62, 0x40, 0x91, 0xbc, 0x4b, 0x76, 0xf0, 0x01, 0x8e, 0xe6, 0x64,
	0x66, 0xbc, 0xa1, 0x0f, 0xb3, 0x28, 0xf0, 0xdc, 0x37, 0xfe, 0x7d, 0xc6, 0xf8, 0x6c, 0xbb, 0xed,
	0xe0, 0x9c, 0xe1, 0x3d, 0x44, 0xa5, 0x58, 0x19, 0x9a, 0x2d, 0x2b, 0x83, 0x43, 0xae, 0x7f, 0xd0,
	0x94, 0xe5, 0x6c, 0x9a, 0xc3, 0x65, 0x23, 0xb2, 0x5a, 0xc9, 0xb7, 0x8c, 0xbe, 0xab, 0x56, 0x72,
	0xd2, 0x9e, 0x79, 0x7a, 0xea, 0x2e, 0xfa, 0x62, 0xeb, 0xc2, 0xee, 0xaa, 0x60, 0xaf, 0x07, 0x6e,
	0x69, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x20, 0x5e, 0x3f, 0xc8, 0x01, 0x00, 0x00,
}
